#pragma once

#ifdef _DEBUG
#pragma comment(lib, "vtkCommonCored.lib")
#pragma comment(lib, "vtkCommonColord.lib")
#pragma comment(lib, "vtkCommonExecutionModeld.lib")
#pragma comment(lib, "vtkCommonDataModeld.lib")
#pragma comment(lib, "vtkCommonMathd.lib")
#pragma comment(lib, "vtkCommonMiscd.lib")
#pragma comment(lib, "vtkCommonSystemd.lib")
#pragma comment(lib, "vtkCommonTransformsd.lib")
#pragma comment(lib, "vtkInteractionWidgetsd.lib")
#pragma comment(lib, "vtkInteractionStyled.lib")
#pragma comment(lib, "vtkRenderingCored.lib")
#pragma comment(lib, "vtkRenderingOpenGL2d.lib")
#pragma comment(lib, "vtkRenderingUId.lib")
#pragma comment(lib, "vtkglewd.lib")
#pragma comment(lib, "vtksysd.lib")
#pragma comment(lib, "vtklogurud.lib")
#pragma comment(lib, "vtkfreetyped.lib")
#pragma comment(lib, "vtkRenderingFreeTyped.lib")
#pragma comment(lib, "vtkFiltersCored.lib")
#pragma comment(lib, "vtkFiltersGenerald.lib")
#pragma comment(lib, "vtkFiltersSourcesd.lib")
#pragma comment(lib, "vtkzlibd.lib")

#else

#pragma comment(lib, "vtkCommonCore.lib")
#pragma comment(lib, "vtkCommonColor.lib")
#pragma comment(lib, "vtkCommonMath.lib")
#pragma comment(lib, "vtkCommonMisc.lib")
#pragma comment(lib, "vtkCommonSystem.lib")
#pragma comment(lib, "vtkCommonTransforms.lib")
#pragma comment(lib, "vtkCommonExecutionModel.lib")
#pragma comment(lib, "vtkCommonDataModeld.lib")
#pragma comment(lib, "vtkInteractionWidgets.lib")
#pragma comment(lib, "vtkCommonDataModeld.lib")
#pragma comment(lib, "vtkInteractionStyle.lib")
#pragma comment(lib, "vtkRenderingCore.lib")
#pragma comment(lib, "vtkRenderingOpenGL2.lib")
#pragma comment(lib, "vtkRenderingUI.lib")
#pragma comment(lib, "vtkglewd.lib")
#pragma comment(lib, "vtksys.lib")
#pragma comment(lib, "vtkloguru.lib")
#pragma comment(lib, "vtkfreetype.lib")
#pragma comment(lib, "vtkRenderingFreeType.lib")
#pragma comment(lib, "vtkFiltersCore.lib")
#pragma comment(lib, "vtkFiltersGeneral.lib")
#pragma comment(lib, "vtkFiltersSources.lib")
#pragma comment(lib, "vtkzlib.lib")
#endif

#include <vtkAutoInit.h>
VTK_MODULE_INIT(vtkRenderingOpenGL2)
VTK_MODULE_INIT(vtkInteractionStyle)
